### ISSUE TITLE
Remove Console.log before publishing

### ISSUE THREAD

**Issue by JasonDevTech** [NiclasDev63/tiptap-extension-auto-joiner#1]
In production, I've noticed a bunch of random console.logs appearing and tracked down the issue to this console.log not being removed.

https://github.com/NiclasDev63/tiptap-extension-auto-joiner/blob/9edebc0d10647b1d9c74e5d2f86cc58632d80bad/src/index.ts#L37-L47

**Comment by NiclasDev63** [comment]
I am going to remove this later and publish a new version to npm

**Comment by NiclasDev63** [comment]
Just published the new version
